# Automatically add labels based on changed file paths
# Make sure you also add the labels in the repo (settings -> labels) or auto-create them.

frontend:
  - "frontend/**"

backend:
  - "backend/**"

infra:
  - "infra/**"

docs:
  - "docs/**"
  - "*.md"
  - ".github/**"

ci:
  - ".github/workflows/**"
  - "ci/**"

release:
  - "CHANGELOG.md"
